version: '3.4'
services:
  sentinel1:
    image: redis
    container_name: redis-cluster-sentinel_1
    #ports:
    #  - 26001:26379
    volumes:
      - ./sentinel1.conf:/usr/local/etc/redis/sentinel.conf
    command: redis-sentinel /usr/local/etc/redis/sentinel.conf

  sentinel2:
    image: redis
    container_name: redis-cluster-sentinel_2
    #ports:
    #  - 26002:26379
    volumes:
      - ./sentinel2.conf:/usr/local/etc/redis/sentinel.conf
    command: redis-sentinel /usr/local/etc/redis/sentinel.conf

  sentinel3:
    image: redis
    container_name: redis-cluster-sentinel_3
    #ports:
    #  - 26003:26379
    volumes:
      - ./sentinel3.conf:/usr/local/etc/redis/sentinel.conf
    command: redis-sentinel /usr/local/etc/redis/sentinel.conf
