#!/bin/bash
#chkconfig: 345 70 70
#description: JBOSS Server
. /etc/init.d/functions
. /etc/profile

RETVAL=$?


APP_HOME=/home/AppDeploy/UMP-client
APP_JAR=ump-client.jar
#UMP_JAVA=/home/AppServer/jdk1.8.0_201


case "$1" in

start)
  ppid=`ps -ef | grep $APP_JAR | grep -v grep | awk '{print $2}'`  
  if [ -z "$ppid" ]; then
      cd $APP_HOME
      java -Dlogback.configurationFile=./config/client_logback.xml -server -jar $APP_HOME/$APP_JAR >>/dev/null 2>&1 &
      pid=`ps -ef | grep $APP_JAR | grep -v grep | awk '{print $2}'`
      echo "$APP_JAR ($pid) application started"
      exit
  else
      echo "UMP Client is already running (pid $ppid)"
      exit
  fi
;;

status)
  ppid=`ps -ef | grep $APP_JAR | grep -v grep | awk '{print $2}'` 
  if [ -z "$ppid" ]; then
      echo "UMP Client is not started..."
	  exit
  else
      echo "UMP Client is running (pid $ppid)"
      exit
  fi
;;

stop)
  ppid=`ps -ef | grep $APP_JAR | grep -v grep | awk '{print $2}'`  
  if [ -z "$ppid" ]; then
      echo "UMP Client is already stopped"
	  exit
   else
	 ps -ef | grep ump-client | grep -v grep | awk '{print $2}'|xargs kill
      echo "UMP Client is stoped(pid $ppid)"
	  exit
   fi
;;

restart)
      $0 stop
	  sleep 10
      $0 start

;;

*)

echo $"Usage: $0 {start|stop|restart|status}"

exit 1

;;

esac

exit $RETVAL
