#!/bin/bash
# chkconfig: 345 70 70 
# description: activemq servlet container.
# Source function library.
. /etc/init.d/functions
# source networking configuration.
. /etc/sysconfig/network
. /etc/profile

#export JAVA_HOME=/usr/local/jdk1.6.0_45/
export CATALINA_HOME=/home/AppServer/apache-activemq-5.10.2-efps/

case $1 in
    start)
        sh $CATALINA_HOME/bin/activemq start
    ;;
    stop)
        sh $CATALINA_HOME/bin/activemq stop
    ;;
    status)
        sh $CATALINA_HOME/bin/activemq status
    ;;
    restart)
        sh $CATALINA_HOME/bin/activemq stop
        sleep 1
        sh $CATALINA_HOME/bin/activemq start
    ;;

esac
exit 0
