master:
  image: wxsc/redis:stable
  ports:
    - "17379:16379"
  container_name: redis-cluster_master
  command: redis-server /etc/redis/redis.conf --port 16379
  net: "host"
slave_1:
  image: wxsc/redis:stable
  container_name: redis-cluster_slave_1
  ports: 
    - "17380:16380"
  command: redis-server /etc/redis/redis.conf --port 16380 --slaveof redis-master 16379
  ports: 
    - "17380:16380"
  net: "host"
slave_2:
  image: wxsc/redis:stable
  container_name: redis-cluster_slave_2
  command: redis-server /etc/redis/redis.conf --port 16381 --slaveof redis-master 16379
  ports:
    - "16381:16381"
  net: "host"
sentinel_1:
  image: wxsc/redis-sentinel:stable
  container_name: redis-cluster_sentinel_1
  command: redis-sentinel /etc/redis/sentinel.conf --port 26379
  environment:
    - SENTINEL_PORT=26379
  ports:
    - "26397:26379"
  net: "host"
sentinel_2:
  image: wxsc/redis-sentinel:stable
  container_name: redis-cluster_sentinel_2
  command: redis-sentinel /etc/redis/sentinel.conf --port 26380
  environment:
    - SENTINEL_PORT=26380
  ports:
    - "26380:26380"
  net: "host"
sentinel_3:
  image: wxsc/redis-sentinel:stable
  container_name: redis-cluster_sentinel_3
  command: redis-sentinel /etc/redis/sentinel.conf --port 26381
  environment:
    - SENTINEL_PORT=26381
  ports:
    - "26381:26381"
  net: "host"

