version: '3.4'
services:
  master:
    image: redis
    container_name: redis-cluster-master
    #restart: always
    ports:
      - 6300:6379
    volumes:
      - "./redis_master.conf:/etc/redis/redis.conf"
    command: redis-server /etc/redis/redis.conf

  slave1:
    image: redis
    container_name: redis-cluster-slave_1
    ports:
      - 6301:6379
    volumes:
      - "./redis_slave_1.conf:/etc/redis/redis.conf"
    command: redis-server /etc/redis/redis.conf --slaveof 192.168.0.102 6300

  slave2:
    image: redis
    container_name: redis-cluster-slave_2
    ports:
      - 6302:6379
    volumes:
      - "./redis_slave_2.conf:/etc/redis/redis.conf"
    command: redis-server /etc/redis/redis.conf --slaveof 192.168.0.102 6300
  sentinel1:
    image: redis
    container_name: redis-cluster-sentinel_1
    ports:
      - 26001:26379
    volumes:
      - "./sentinel1.conf:/usr/local/etc/redis/sentinel.conf"
    command: redis-sentinel /usr/local/etc/redis/sentinel.conf

  sentinel2:
    image: redis
    container_name: redis-cluster-sentinel_2
    ports:
      - 26002:26379
    volumes:
      - "./sentinel2.conf:/usr/local/etc/redis/sentinel.conf"
    command: redis-sentinel /usr/local/etc/redis/sentinel.conf

  sentinel3:
    image: redis
    container_name: redis-cluster-sentinel_3
    ports:
      - 26003:26379
    volumes:
      - "./sentinel3.conf:/usr/local/etc/redis/sentinel.conf"
    command: redis-sentinel /usr/local/etc/redis/sentinel.conf 
