global:
  scrape_interval:     15s
  evaluation_interval: 15s
scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']
        labels:
          instance: prometheus
          
  - job_name: linux1
    static_configs:
      - targets: ['192.168.11.103:9100']
        labels:
          instance: sys1
          
  - job_name: linux2
    static_configs:
      - targets: ['192.168.11.102:9100']
        labels:
          instance: sys2

  - job_name: redis103_9121
    static_configs:
     - targets: ['192.168.11.103:9121']
       labels:
         instance: redis_9121


  - job_name: mysql217_9104
    static_configs:
     - targets: ['192.168.11.217:9104']
       labels:
         instance: mysql217_9104

